### ISSUE TITLE
App crashes, whenever news list is scrolled 

### ISSUE THREAD

**Issue by someuser10** [AmrAbdelhameed/NYTimesMostPopularArticles_MVVM_Kotlin#1]
`val imageUrl: ObservableField<String?> =
        ObservableField(article.media?.get(0)?.mediametadata?.get(1)?.url)`

this is causing `IndexOutOfBoundsException`.

> D/AndroidRuntime: Shutting down VM
> E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.example.nytimesmostpopulararticles_mvvm_kotlin, PID: 9563
>     java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
>         at java.util.ArrayList.get(ArrayList.java:437)
>         at com.example.nytimesmostpopulararticles_mvvm_kotlin.ui.main.article.ArticleItemViewModel.<init>(ArticleItemViewModel.kt:12)
>         at com.example.nytimesmostpopulararticles_mvvm_kotlin.ui.main.article.ArticleAdapter$ArticleViewHolder.onBind(ArticleAdapter.kt:56)
>         at com.example.nytimesmostpopulararticles_mvvm_kotlin.ui.base.BaseRecyclerViewAdapter.onBindViewHolder(BaseRecyclerViewAdapter.kt:8)
>         at com.example.nytimesmostpopulararticles_mvvm_kotlin.ui.base.BaseRecyclerViewAdapter.onBindViewHolder(BaseRecyclerViewAdapter.kt:5)
>         at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
>         at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
>         at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
>         at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
>         at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
>         at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
>         at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
>         at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
>         at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
>         at android.os.Handler.handleCallback(Handler.java:883)
>         at android.os.Handler.dispatchMessage(Handler.java:100)
>         at android.os.Looper.loop(Looper.java:214)
>         at android.app.ActivityThread.main(ActivityThread.java:7356)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by AmrAbdelhameed** [comment]
Thanks a lot @someuser10 
The issue has been done, Please try again now.
The issue was that API of NYTimes sometimes returns media empty list and i haven't handled it.

**Comment by someuser10** [comment]
@AmrAbdelhameed I've checked it out, working now.
this project is beautifully organized. Keep it up!

**Comment by AmrAbdelhameed** [comment]
@someuser10 Thanks.
